services:
  postgres:
    image: postgis/postgis:18-3.6-alpine
    container_name: postgres_cap2
    environment:
      POSTGRES_DB: vat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # change if needed (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local